on:
  push:
    branches:
      - main
    paths-ignore:
      - "terraform/**"
      - ".github/**"
      - ".vscode/**"
      - "README.md"
      - "catalog-info.yaml"
      - ".gitignore"
      - "LICENSE"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: echo Print!