on:
  push:
    branches:
      - main
    paths-ignore:
      - "terraform"
      - "README.md"
      - "catalog-info.yaml"
      - ".github"
      - ".vscode"
      - ".gitignore"
      - "LICENSE"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: echo Print!